import json
import os
import re
from typing import Any

import azure.durable_functions as df
import azure.functions as func
from azure.identity import DefaultAzureCredential, get_bearer_token_provider
from openai import AzureOpenAI

app = df.DFApp(http_auth_level=func.AuthLevel.FUNCTION)


def json_response(payload: dict[str, Any], status_code: int = 200) -> func.HttpResponse:
    return func.HttpResponse(
        json.dumps(payload),
        status_code=status_code,
        mimetype='application/json',
    )


def configured_openai_client() -> tuple[AzureOpenAI, str]:
    endpoint = os.environ.get('AZURE_OPENAI_ENDPOINT')
    deployment = os.environ.get('AZURE_OPENAI_DEPLOYMENT')
    api_version = os.environ.get('AZURE_OPENAI_API_VERSION')

    if not endpoint or not deployment or not api_version:
        raise RuntimeError('Azure OpenAI configuration is incomplete.')

    token_provider = get_bearer_token_provider(
        DefaultAzureCredential(),
        'https://cognitiveservices.azure.com/.default',
    )
    return (
        AzureOpenAI(
            azure_endpoint=endpoint,
            api_version=api_version,
            azure_ad_token_provider=token_provider,
        ),
        deployment,
    )


@app.route(route='health', methods=['GET'], auth_level=func.AuthLevel.ANONYMOUS)
def health(req: func.HttpRequest) -> func.HttpResponse:
    return json_response({'status': 'ok'})


@app.route(route='llm-ping', methods=['GET'], auth_level=func.AuthLevel.FUNCTION)
def llm_ping(req: func.HttpRequest) -> func.HttpResponse:
    try:
        client, deployment = configured_openai_client()
        completion = client.chat.completions.create(
            model=deployment,
            messages=[{'role': 'user', 'content': 'Reply with exactly: pong'}],
            max_tokens=8,
        )
    except Exception:
        return json_response({'error': 'Unable to contact the configured LLM.'}, status_code=502)

    return json_response(
        {
            'response': completion.choices[0].message.content,
            'tokens': {
                'prompt': completion.usage.prompt_tokens if completion.usage else None,
                'completion': completion.usage.completion_tokens if completion.usage else None,
                'total': completion.usage.total_tokens if completion.usage else None,
            },
        }
    )


def validated_generation_request(req: func.HttpRequest) -> tuple[dict[str, Any] | None, str | None]:
    try:
        body = req.get_json()
    except ValueError:
        return None, 'Request body must be valid JSON.'

    if not isinstance(body, dict):
        return None, 'Request body must be a JSON object.'

    topic = body.get('topic')
    audience = body.get('audience')
    sources = body.get('sources')
    if not isinstance(topic, str) or not topic.strip():
        return None, 'topic must be a non-empty string.'
    if not isinstance(audience, dict):
        return None, 'audience must be an object.'
    if not isinstance(sources, list):
        return None, 'sources must be an array.'

    return {'topic': ' '.join(topic.split()), 'audience': audience, 'sources': sources}, None


def placeholder_skill_markdown(topic: str) -> str:
    skill_name = re.sub(r'[^a-z0-9]+', '-', topic.lower()).strip('-') or 'generated-skill'
    return (
        f'---\nname: {skill_name}\n'
        f'description: Draft skill for {topic}.\n---\n\n'
        f'# {topic}\n\n'
        'This is a placeholder generated by the Durable Functions baseline.\n'
    )


async def start_generation(
    req: func.HttpRequest, client: df.DurableOrchestrationClient
) -> func.HttpResponse:
    payload, error = validated_generation_request(req)
    if error:
        return json_response({'error': error}, status_code=400)

    instance_id = await client.start_new('skill_generation_orchestrator', None, payload)
    return json_response({'jobId': instance_id, 'status': 'queued'}, status_code=202)


@app.route(route='generate', methods=['POST'], auth_level=func.AuthLevel.FUNCTION)
@app.durable_client_input(client_name='client')
async def generate(req: func.HttpRequest, client: df.DurableOrchestrationClient) -> func.HttpResponse:
    return await start_generation(req, client)


async def generation_status(
    req: func.HttpRequest, client: df.DurableOrchestrationClient
) -> func.HttpResponse:
    instance_id = req.route_params.get('instance_id')
    if not instance_id:
        return json_response({'error': 'instance_id is required.'}, status_code=400)

    status = await client.get_status(instance_id)
    if not status:
        return json_response({'error': 'Generation job not found.'}, status_code=404)

    payload = status.to_json()
    return json_response(
        {
            'jobId': payload.get('instanceId'),
            'status': payload.get('runtimeStatus'),
            'result': payload.get('output'),
            'error': payload.get('customStatus'),
        }
    )


@app.route(route='generate/{instance_id}', methods=['GET'], auth_level=func.AuthLevel.FUNCTION)
@app.durable_client_input(client_name='client')
async def get_generation_status(
    req: func.HttpRequest, client: df.DurableOrchestrationClient
) -> func.HttpResponse:
    return await generation_status(req, client)


@app.orchestration_trigger(context_name='context')
def skill_generation_orchestrator(context: df.DurableOrchestrationContext):
    payload = context.get_input()
    result = yield context.call_activity('generate_skill_markdown', payload)
    return result


@app.activity_trigger(input_name='payload')
def generate_skill_markdown(payload: dict) -> dict[str, str]:
    return {'skill.md': placeholder_skill_markdown(payload['topic'])}
