import json
import os
import re
from typing import Any

import azure.functions as func
from azure.identity import DefaultAzureCredential, get_bearer_token_provider
from openai import AzureOpenAI

app = func.FunctionApp(http_auth_level=func.AuthLevel.FUNCTION)


def json_response(payload: dict[str, Any], status_code: int = 200) -> func.HttpResponse:
    return func.HttpResponse(
        json.dumps(payload),
        status_code=status_code,
        mimetype='application/json',
    )


def configured_openai_client() -> tuple[AzureOpenAI, str]:
    endpoint = os.environ.get('AZURE_OPENAI_ENDPOINT')
    deployment = os.environ.get('AZURE_OPENAI_DEPLOYMENT')
    api_version = os.environ.get('AZURE_OPENAI_API_VERSION')

    if not endpoint or not deployment or not api_version:
        raise RuntimeError('Azure OpenAI configuration is incomplete.')

    token_provider = get_bearer_token_provider(
        DefaultAzureCredential(),
        'https://cognitiveservices.azure.com/.default',
    )
    return (
        AzureOpenAI(
            azure_endpoint=endpoint,
            api_version=api_version,
            azure_ad_token_provider=token_provider,
        ),
        deployment,
    )


@app.route(route='health', methods=['GET'], auth_level=func.AuthLevel.ANONYMOUS)
def health(req: func.HttpRequest) -> func.HttpResponse:
    return json_response({'status': 'ok'})


@app.route(route='llm-ping', methods=['GET'], auth_level=func.AuthLevel.FUNCTION)
def llm_ping(req: func.HttpRequest) -> func.HttpResponse:
    try:
        client, deployment = configured_openai_client()
        completion = client.chat.completions.create(
            model=deployment,
            messages=[{'role': 'user', 'content': 'Reply with exactly: pong'}],
            max_tokens=8,
        )
    except Exception:
        return json_response({'error': 'Unable to contact the configured LLM.'}, status_code=502)

    return json_response(
        {
            'response': completion.choices[0].message.content,
            'tokens': {
                'prompt': completion.usage.prompt_tokens if completion.usage else None,
                'completion': completion.usage.completion_tokens if completion.usage else None,
                'total': completion.usage.total_tokens if completion.usage else None,
            },
        }
    )


@app.route(route='generate', methods=['POST'], auth_level=func.AuthLevel.FUNCTION)
def generate(req: func.HttpRequest) -> func.HttpResponse:
    try:
        body = req.get_json()
    except ValueError:
        return json_response({'error': 'Request body must be valid JSON.'}, status_code=400)

    if not isinstance(body, dict):
        return json_response({'error': 'Request body must be a JSON object.'}, status_code=400)

    topic = body.get('topic')
    audience = body.get('audience')
    sources = body.get('sources')
    if not isinstance(topic, str) or not topic.strip():
        return json_response({'error': 'topic must be a non-empty string.'}, status_code=400)
    if not isinstance(audience, dict):
        return json_response({'error': 'audience must be an object.'}, status_code=400)
    if not isinstance(sources, list):
        return json_response({'error': 'sources must be an array.'}, status_code=400)

    normalized_topic = ' '.join(topic.split())
    skill_name = re.sub(r'[^a-z0-9]+', '-', normalized_topic.lower()).strip('-') or 'generated-skill'
    skill_markdown = (
        f'---\nname: {skill_name}\n'
        f'description: Draft skill for {normalized_topic}.\n---\n\n'
        f'# {normalized_topic}\n\n'
        'This is a placeholder generated by the Azure Function baseline.\n'
    )
    return json_response({'skill.md': skill_markdown})
